apiVersion: v1
kind: Pod
metadata:
  name: readness-demo
spec:
  containers:
  - name: readness-demo-container
    image: fangjiaxiaobai/my-app:v1
    imagePullPolicy: IfNotPresent
    readinessProbe:
      httpGet:
        port: 80
        path: /index1.html
      initialDelaySeconds: 1
      periodSeconds: 3
