apiVersion: batch/v1
kind: CronJob
metadata:
  name: cron-job-demo
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: cron-job-demo-container
            image: busybox
            args:
            - /bin/sh
            - -c
            - date; echo 'hello ,I‘m from K8s cluster.'  
          restartPolicy: OnFailure
